Repository JetBrains/intellij-platform-plugin-template, pull requests merged in 2023-08, with the labels that each got.

#391 (🎁) Add Foojay toolchain provider plugin
  CHANGELOG.md
  settings.gradle.kts
Labels: enhancement

#385 Fix Upload Code Coverage Report step
  .github/workflows/build.yml
Labels: bug

#387 Fix text of button "Install" in generated README.md
  .github/template-cleanup/README.md
Labels: documentation
